### ISSUE TITLE
Mod SDK

### ISSUE THREAD

**Issue by hammermaps** [SamVanheer/HLEnhanced#14]
Can Upload the Mod SDK with sprites, sounds... 

Thx.
Nice Projekt! :+1:

**Comment by SamVanheer** [comment]
You mean you want me to upload the complete SDK? You can download it on Steam, everything except for the source code is in that. It includes Condition Zero models too if you have need for them.

**Comment by hammermaps** [comment]
OK, thx

**Comment by JoelTroch** [comment]
Also, look at [HLEnhanced-Game](https://github.com/SamVanheer/HLEnhanced-Game) repository?

**Comment by hammermaps** [comment]
[https://github.com/SamVanheer/HLEnhanced-Game](url)
