### ISSUE TITLE
SetNextThink Optimization / Enhancement

### ISSUE THREAD

**Issue by hammermaps** [SamVanheer/HLEnhanced#17]
Can you do something like this ?

```
	/**
	*	Sets the next think time.
	*	@param The next think time delay without gpGlobals->time, only the delay.
	*   @param Set is_delay to false, use nextthink without gpGlobals->time.
	*/
	void SetNextThink(const float delay = 0.0, const bool is_delay = true)
	{
		if (is_delay) {
			float m_fNextThink = UTIL_WeaponTimeBase() + delay;
			pev->nextthink = m_fNextThink;
			return;
		}

		pev->nextthink = delay;
	}
```
Old:
`SetNextThink( gpGlobals->time + 0.01 );`

New:
`SetNextThink( 0.01 );`

Or:
`pev->nextthink = pev->ltime + m_flWait;`
New:
`SetNextThink( pev->ltime + m_flWait , false ); //nextthink without gpGlobals->time`

Greetings from Germany

**Comment by SamVanheer** [comment]
UTIL_WeaponTimeBase is intended for use with weapon prediction only, it's never used for nextthink. It always returns 0 anyway in codebases that use weapon prediction. I see what you're getting at, but right now the codebase isn't ready for such a change.

**Comment by hammermaps** [comment]
Ah, ok, was just an idea #

**Comment by JoelTroch** [comment]
This comes from SoHL right ?
