### ISSUE TITLE
LINK : fatal error LNK1104: cannot open file '../hl.def'

### ISSUE THREAD

**Issue by Sayok6** [SamVanheer/HLEnhanced#31]
I was compiling the hl project apart of HLEnhanced.sln, and this error popped up. There were no other errors, and the only box I checked during the CMake part was 'USE_OPFOR'.

**Comment by SamVanheer** [comment]
Did you put the CMake build directory inside the main repository directory? Currently hl.def is located in that directory, and the build directory must be located relative to that directory. I know of a way to remove the need for that file but i won't be able to add that right away.

**Comment by Sayok6** [comment]
I did put the CMake build directory inside the main repository. Do I just put the build directory the directory before it, or just a new directory entirely?

**Comment by SamVanheer** [comment]
I put my build directory in /projects_msw14, and /projects_Linux for Linux builds. If your build directory is in such a directory it should work.

**Comment by JoelTroch** [comment]
Furthermore, you shouldn't use the root folder as "Build directory" as this will trigger circular dependencies warnings with CMake.

**Comment by SamVanheer** [comment]
Commit 693fe6e0018c133fcf69e6993fb233f023e8dd43 added the copying of the file to the binary directory, which allows out-of-source builds. That resolves this issue.
