### ISSUE TITLE
IBaseUI has wrong name

### ISSUE THREAD

**Issue by tmp64** [SamVanheer/HLEnhanced#45]
While working on GameUI panels support for [BugfixedHL/GameUIPanels](https://github.com/tmp64/BugfixedHL/tree/GameUIPanels), I noticed that IBaseUI's name is VEngineVGui001. That name actually belongs to [IEngineVGui](https://github.com/ValveSoftware/source-sdk-2013/blob/master/sp/src/public/ienginevgui.h). IBaseUI's name should probably be BaseUI001 (based on `strings gameui.so | grep BaseUI`).

**Comment by SamVanheer** [comment]
Thanks, i've corrected it.
