### ISSUE TITLE
[Windows / VS2015] ServerInterface - macro redefinition

### ISSUE THREAD

**Issue by JoelTroch** [SamVanheer/HLEnhanced#5]
game\server\ServerInterface.cpp - Line 513-515

```cpp
ExternC PfnDliHook __pfnDliNotifyHook2 = DelayHook;

ExternC PfnDliHook   __pfnDliFailureHook2 = nullptr;
```

'__pfnDliNotifyHook2' : redefinition ; modifiers of different types (C2373)
'__pfnDliFailureHook2' : redefinition ; modifiers of different types (C2373)

**Comment by SamVanheer** [comment]
This appears to be an issue caused by Visual Studio 2015 update 3. It includes safer versions of these globals that are declared const in the header. I'll update my installation and then update the code to account for this so it compiles for both pre update 3 and post update 3 installations.

**Comment by SamVanheer** [comment]
I've fixed this issue by disabling the const declarations. It should compile properly now.
