### ISSUE TITLE
[Wiki] Home, Compiling and features pages "PR"

### ISSUE THREAD

**Issue by JoelTroch** [SamVanheer/HLEnhanced#6]
I started writing some Wiki pages on my fork that explain how to compile the SDK (Windows only for the time being) and the features list. I wanted to make a PR but sadly, GitHub denies Wiki PRs, so feel free to copy/paste or do whatever you want with it.

**Comment by SamVanheer** [comment]
Thanks, looks very interesting :)
I can enable editing for non-collaborators so you can edit this repository's wiki directly if that's what you want.

**Comment by JoelTroch** [comment]
As you wish ^^

**Comment by SamVanheer** [comment]
I've changed the setting so anyone can edit the wiki.

**Comment by JoelTroch** [comment]
Closing this because anyone has the permission to edit the wiki.
